#!/bin/bash

src=root@sodium:/srv/public/pkg/apk

sed -e 's:#.*$::g' -e '/\s*#.*$/d' -e '/^\s*$/d' | (

while read apk
do
  echo -e "-----------------------\nGetting $src/$apk ..."
  rsync -av "$(printf '%q' "$src/$apk")" .
done

)
